### ISSUE TITLE
Keyboard doesn't work on Macbook 2016-2017

### ISSUE THREAD

**Issue by wizz777** [zhovner/OneFileLinux#1]
After reboot on Linux don't work keyboard 
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)

**Comment by zhovner** [comment]
Thank you for your report. Will check this soon.

**Comment by zhovner** [comment]
Can you please connect USB keyboard and show me `lspci -nn`.
Photo will be enough.

**Comment by wizz777** [comment]
![g3rse5lld34](https://user-images.githubusercontent.com/25935350/36627865-6339a25e-195a-11e8-823c-59c810936ea2.jpg)

**Comment by Lalabuy948** [comment]
Same problem with keyboard. Model: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)

**Comment by zhovner** [comment]
New macbook's have SPI keyboard that not supported officially in Linux. 
Here the work-in-progress driver https://github.com/cb22/macbook12-spi-driver/issues/49
 
I add this driver in testing build.
Try this one please: [OneFileLinux_macbook-spi-keyboard-driver.zip](https://zhovner.com/tmp/OneFileLinux_macbook-spi-keyboard-driver.zip)

**Comment by Lalabuy948** [comment]
It works! But font is too small

2018-02-28 8:29 GMT+01:00 Pavel Zhovner <notifications@github.com>:

**Comment by zhovner** [comment]
Okay. Now we need to figure out how to automatically check what version of macbook we have while boot. Because macbook12 2015 need different drivers set. 

Script should do:
1. Check if booting on macbook
2. If macbook12 2015 — load one driver 
3. If macbook 2016-2017 — load another driver

**Comment by zhovner** [comment]
Done. New script `/etc/init.d/macbook` automatically check hardware version and loads necessary drivers. Also font size fixed.

Now you can change font size with command: `fontsize 9`
