### ISSUE TITLE
.config options to build with newer kernel

### ISSUE THREAD

**Issue by Patazerty** [zhovner/OneFileLinux#11]
I'm trying to make a custom build with a more up-to-date kernel, but so far it always end up with a kernel panic `not syncing: VFS: Unable to mount root fs on unknown-block(0,0)`. I'm certainly missing something in my .config. What are the key kernel config elements to set to get a functional build ?

**Comment by zhovner** [comment]
Do you use virtual machine image?

**Comment by Patazerty** [comment]
I tried using the VM, it did not change the result. I can build a working .efi using the kernel and .config included in the repo, but as soon as I try to use another kernel source, I have the mount error. Even with the same 4.14.22 kernel version from kernel.org and the .config of the repo. So my question is about the changes you made to the kernel source/config to get it working, I can't see what I'm missing here. Thanks !

**Comment by zhovner** [comment]
Honestly i don't remember anything of this project :)
I modified the kernel sources to apply a patch for macbook SPI keyboard, probably that's all and this should not refer to your error. 
Do you use my `build.sh` script? Is root fs builds correctly?

**Comment by Patazerty** [comment]
Turns out the kernel config was fine, I just forgot to put the `init` file at the root of the alpine minirootfs with the `INITRAMFS=1` export. I took your build script and modified it to my needs, using a newer kernel and alpine minirootfs. My build now boots fine, thanks !

**Comment by zhovner** [comment]
Pull request are welcome.
