### ISSUE TITLE
Setting kernel config

### ISSUE THREAD

**Issue by VerTiGoEtrex** [zhovner/OneFileLinux#12]
Hi, trying to recreate this from scratch in a docker container for the heck of it, and because it's _super cool_!

How did you learn to set the right `.config` options for the Linux kernel? In particular, getting the right Wifi drivers, removing unnecessary modules, etc?

I tried copying [this config](https://raw.githubusercontent.com/alpinelinux/aports/master/main/linux-vanilla/config-vanilla.x86_64) from the official alpine kernel packages, but it's unnecessarily huge, including a bunch of nvidia graphics drivers, ETC. that are not needed for simple wifi packet injection/sniffing. I could try slimming that one down manually, but it seems like you probably didn't do that, and it would take forever, too.

Any basic instructions on how to recreate your `.config` file?

**Comment by zhovner** [comment]
>How did you learn to set the right .config options for the Linux kernel?

There is a documentation in `make menuconfig` for every option.

**Comment by VerTiGoEtrex** [comment]
You manually combed through every option?

**Comment by zhovner** [comment]
>You manually combed through every option?

I've tried again and again.

**Comment by VerTiGoEtrex** [comment]
Wow... Alright, I'll see what I can do. Thanks.

It seems it should be possible to boot a normal live-usb install of Alpine and then use the `localmodconfig` make target of the kernel sources to trim down to only the exact set of modules that are actually being used. I'll give it a shot and comment back here if it works.
