### ISSUE TITLE
Add my script to repo plz

### ISSUE THREAD

**Issue by foxpdll** [zhovner/OneFileLinux#15]
I have rebuild with latest kernel and minifs.
And rewrite some scripts to build from zerro.
Scripts worked fine on ubuntu 18.04 kernel 5.6.8 and alpine-minirootfs-3.11.6

[OneFileLinuxFoxPDLL.tar.gz](https://github.com/zhovner/OneFileLinux/files/4566744/OneFileLinuxFoxPDLL.tar.gz)

**Comment by zhovner** [comment]
Cool! Can you please make a pull request instead of archive?

**Comment by foxpdll** [comment]
I wil try but i never do that. My sorry if i will do thome thing wrong

**Comment by zhovner** [comment]
1. Fork my repo
2. Clone your fork to your local computer
3. add files to your local repo and push it to github
4. Press "pull request" on your repo on github
