### ISSUE TITLE
Driver for Broadcom BCM4331 Wireless Chipset

### ISSUE THREAD

**Issue by osteotek** [zhovner/OneFileLinux#4]
MacbookPro 10.1 (retina mid-2012) has a Broadcom BCM4331 Wireless Chipset.
Open-source driver is built-in to the kernel (b43) but requires non-free firmware to function. See http://linuxwireless.sipsolutions.net/en/users/Drivers/b43/ or https://aur.archlinux.org/packages/b43-firmware/

There is also proprietary driver from Broadcom found here: https://www.broadcom.com/support/download-search/?pf=Wireless+LAN+Infrastructure

What can be a best way to integrate one of these into OneFileLinux?

**Comment by osteotek** [comment]
AFAIK, open-source driver for BCM4331 also allows monitor mode and injection, that can be useful

**Comment by zhovner** [comment]
Okay, will add it in next release.

**Comment by zhovner** [comment]
Done. Please test new release.

Also be aware, that this is `wl-6.30.163.46` version. Many distros including Kali Linux use `wl-5.100.138` version.

**Comment by osteotek** [comment]
Tested, wireless card is detected and I'm able to scan networks, enter monitor mode, etc. Thanks!
Didn't succeed in connecting to my network with wpa_supplicant, though. Not sure if it's related to the driver or I'm doing something wrong. Also, is there really no dhcp-client installed?

**Comment by zhovner** [comment]
>no DHCP client is available, right?

It's called `udhcpc`, built in `busybox` DHCP client.
I can't create symlink like familiar `dhclient` because busybox can recognise only it's own names.

**Comment by zhovner** [comment]
Try this manual https://github.com/zhovner/OneFileLinux/wiki/How-to-connect-to-WiFi
